### ISSUE TITLE
Some elements are selectable

### ISSUE THREAD

**Issue by floriancargoet** [breach/mod_strip#22]
Double clicking the back or forward button or focussing the strip and hitting Cmd+A selects some elements and it's a bit ugly. I don't expect browser UI elements to be selectable.

![screenshot](https://cloud.githubusercontent.com/assets/110431/3552440/67f90770-08f7-11e4-90dc-37d31e1ed5bc.png)

The fix is simple : 

``` css
body {
    -webkit-user-select: none;
}
```
